"""
Integration Tests for Sandra's Emergency Alerts & Simulators
============================================================
Verifies end-to-end telemetry generation, rules evaluation,
alert deduplication, and schema conformance to shared/schemas/event_schema.json.
"""

import json
from pathlib import Path
import pytest

from sandra.emergency_alerts.src.rules_engine import RulesEngine
from sandra.emergency_alerts.src.deduplicator import AlertDeduplicator
from sandra.emergency_alerts.src.priority_queue import PriorityAlertManager
from sandra.emergency_alerts.src.models import (
    PatientRecord,
    VitalSigns,
    IVDripState,
    ECGState,
    AlertStatus,
    SeverityLevel,
)
from simulator.emergency_simulator.scenario_runner import ScenarioRunner
from simulator.emergency_simulator.emergency_scenarios import SCENARIOS


@pytest.fixture
def test_setup():
    rules_engine = RulesEngine()
    dedup = AlertDeduplicator(cooldown_seconds=1.0)
    alert_mgr = PriorityAlertManager()

    patient = PatientRecord(
        patient_id="P001",
        room_id="ROOM101",
        name="Eleanor Vance",
        age=72,
        gender="Female",
        admission_date="2026-09-10T08:30:00Z",
        condition="Post-operative recovery",
        status="Observation",
        assigned_doctor="Dr. Sarah Chen",
        assigned_nurse="Nurse Alex Taylor",
        devices_connected=["ECG_MONITOR", "PULSE_OXIMETER", "IV_DRIP"],
        vitals=VitalSigns(heart_rate=74, blood_pressure="125/80", systolic_bp=125, diastolic_bp=80, spo2=97, respiratory_rate=16, temperature=36.8),
        iv_drip=IVDripState(volume_remaining_ml=500.0, flow_rate_ml_h=100.0, status="NORMAL"),
        ecg=ECGState(rhythm="NORMAL_SINUS_RHYTHM", status="NORMAL"),
    )

    store = {"P001": patient, "P002": patient, "P003": patient, "P004": patient}
    runner = ScenarioRunner(rules_engine, dedup, alert_mgr, store)
    return runner, alert_mgr, store


def test_schema_compliance_of_all_scenarios(test_setup):
    """
    Validates that events generated by all scenarios strictly adhere to shared/schemas/event_schema.json.
    """
    runner, alert_mgr, _ = test_setup
    schema_path = Path("shared/schemas/event_schema.json")
    assert schema_path.exists(), "Event schema must exist"
    with open(schema_path, "r", encoding="utf-8") as f:
        schema = json.load(f)

    required_fields = set(schema.get("required", []))
    allowed_severities = set(schema["properties"]["severity"]["enum"])
    allowed_statuses = set(schema["properties"]["status"]["enum"])

    # Test each single-scenario
    for sc_id in SCENARIOS.keys():
        alert_mgr.clear_all()
        res = runner.execute_scenario(sc_id)
        assert res["status"] == "SUCCESS"

        alerts = alert_mgr.get_all_alerts()
        for alert in alerts:
            # Check mandatory event schema fields
            assert alert.event_id
            assert alert.patient_id
            assert alert.room_id
            assert alert.parameter
            assert alert.unit
            assert alert.severity.value in allowed_severities
            assert alert.status.value in allowed_statuses
            assert alert.message


def test_scenario_low_spo2_alert_generation(test_setup):
    runner, alert_mgr, store = test_setup
    res = runner.execute_scenario("LOW_SPO2", "P001")
    assert res["status"] == "SUCCESS"
    alerts = alert_mgr.get_all_alerts(status=AlertStatus.ACTIVE, patient_id="P001")
    assert len(alerts) >= 1
    spo2_alert = next((a for a in alerts if a.parameter == "spo2"), None)
    assert spo2_alert is not None
    assert spo2_alert.severity == SeverityLevel.CRITICAL
    assert spo2_alert.value == 82.0


def test_scenario_drip_empty_alert_generation(test_setup):
    runner, alert_mgr, store = test_setup
    res = runner.execute_scenario("DRIP_FINISHED", "P001")
    assert res["status"] == "SUCCESS"
    alerts = alert_mgr.get_all_alerts(status=AlertStatus.ACTIVE, patient_id="P001")
    drip_alert = next((a for a in alerts if a.parameter == "iv_drip_volume"), None)
    assert drip_alert is not None
    assert drip_alert.severity == SeverityLevel.CRITICAL
    assert drip_alert.value == 0.0


def test_scenario_ecg_arrhythmia_generation(test_setup):
    runner, alert_mgr, store = test_setup
    res = runner.execute_scenario("ECG_ARRHYTHMIA", "P001")
    assert res["status"] == "SUCCESS"
    alerts = alert_mgr.get_all_alerts(status=AlertStatus.ACTIVE, patient_id="P001")
    ecg_alert = next((a for a in alerts if a.parameter == "ecg_rhythm"), None)
    assert ecg_alert is not None
    assert ecg_alert.severity == SeverityLevel.CRITICAL
    assert ecg_alert.value == "VENTRICULAR_FIBRILLATION"


def test_scenario_normal_baseline_restores_and_resolves(test_setup):
    runner, alert_mgr, store = test_setup
    # First trigger crisis
    runner.execute_scenario("HIGH_HEART_RATE", "P001")
    assert len(alert_mgr.get_all_alerts(status=AlertStatus.ACTIVE)) > 0

    # Trigger normal baseline
    res = runner.execute_scenario("NORMAL_BASELINE", "P001")
    assert res["status"] == "SUCCESS"
    active_alerts = alert_mgr.get_all_alerts(status=AlertStatus.ACTIVE, patient_id="P001")
    assert len(active_alerts) == 0
    resolved_alerts = alert_mgr.get_all_alerts(status=AlertStatus.RESOLVED, patient_id="P001")
    assert len(resolved_alerts) > 0


def test_multi_patient_crisis_scenario(test_setup):
    runner, alert_mgr, store = test_setup
    res = runner.execute_scenario("MULTI_PATIENT_CRISIS")
    assert res["status"] == "SUCCESS"
    alerts = alert_mgr.get_all_alerts(status=AlertStatus.ACTIVE)
    assert len(alerts) >= 3
    # Check that critical alerts are present
    critical_alerts = [a for a in alerts if a.severity == SeverityLevel.CRITICAL]
    assert len(critical_alerts) >= 2
